version: '3.8'

services:
  tinvest:
    build:
      context: .
      dockerfile: Dockerfile.TinvestGateway
    ports:
      - "8085:8085"
    networks:
      - infra_default

networks:
  infra_default:
    external: true
    driver: bridge