services:
  tinvest:
    build:
      context: .
      dockerfile: Dockerfile.TinvestGateway
    ports:
      - "8085:8080"
    networks:
      - infra_default
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker 

networks:
  infra_default:
    external: true
    driver: bridge